# Emojis

name: emojis 
parent: default

matches:
  - trigger: ":lol"
    replace: "😂"
  - trigger: ":llol"
    replace: "😂😂😂😂"
  - trigger: ":sad"
    replace: "😢"
  - trigger: ":sml"
    replace: "😊"
  - trigger: ":strong"
    replace: "💪"
  - trigger: ":stlol"
    replace: "💪😂"
  - trigger: ":ba"
    replace: "😎"
  - trigger: ":+1"
    replace: "👍"
  - trigger: ":ok"
    replace: "👌"
  - trigger: ":happy"
    replace: "😄"
  - trigger: ":cry"
    replace: "😭"
  - trigger: ":wow"
    replace: "😮"